StudentenHuis/Components/SidebarViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StudentenHuis.Models;
using StudentenHuis.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace StudentenHuis.Components
{
    public class SidebarViewComponent : ViewComponent
    {
        private IMealRepository Meal;
        private UserManager<ApplicationUser> UserManager;
        public SidebarViewComponent(IMealRepository repo, UserManager<ApplicationUser> UserManager)
        {
            Meal = repo;
            this.UserManager = UserManager;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var User = HttpContext.User;
            string UserID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ApplicationUser ApplicationUser = null;
            if (UserID != null) ApplicationUser = await UserManager.FindByIdAsync(UserID);
            return View(new SideBarViewModel(Meal, ApplicationUser));
        }
    }
}

StudentenHuis/Controllers/MealController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StudentenHuis.Models;
using StudentenHuis.Models.ViewModels;

namespace StudentenHuis.Controllers
{
    public class MealController : Controller
    {
        // Meal repository om de maaltijden op te halen
        private IMealRepository MealRepository;

        // User repository voor validaties
        private IUserRepository UserRepository;

        // Constructor met twee dependencies 
        public MealController(IMealRepository MealRepository, IUserRepository UserRepository)
        {
            this.MealRepository = MealRepository;
            this.UserRepository = UserRepository;
        }

        // Index pagina met een lijst aan maaltijden in de komende twee weken en vandaag
        public ViewResult Index()
        {
            return View(MealRepository.Meals.Where(e => e.Date.Date.CompareTo(DateTime.Now.Date) >= 0).Where(e => e.Date.Date.CompareTo(DateTime.Now.Date.AddDays(14)) < 0).ToList());
        }

        
        // Detail pagina voor gedetailleerde informatie over een maaltijd
        public ViewResult Detail(int ID)
        {
            return View(MealRepository.Meals.Where(e => e.ID == ID).FirstOrDefault());
        }

        // Nieuwe maaltijden mogen alleen aangemaakt worden door een ingelogde student
        [Authorize]

        // Nieuwe maaltijd
        public ViewResult NewMeal()
        {
            return View(new Meal());
        }

        // Een maaltijd aanpassen, de informatie over de maaltijd wordt meegegeven
        [Authorize]
        public ViewResult EditMeal(int ID)
        {
            return View(MealRepository.Meals.Where(e => e.ID == ID).FirstOrDefault());
        }

        // De POST request om de meal aan te passen
        [Authorize]
        [HttpPost]
        public IActionResult EditMeal(Meal Meal)
        {
            // In het geval dat het aantal eters niet 0 is dan geven we een error (zou niet mogelijk moeten zijn)
            if (Meal.Eaters.Count != 0) return Redirect("/Error");
            // Kijk of het succesvol is gegaan en redirect dan terug naar de maaltijd pagina

            // Bekijk of gebruiker wel de kok is
            if (User != null && !Meal.Cook.Id.Equals(User.FindFirstValue(ClaimTypes.NameIdentifier))) return View("Error");

            if (MealRepository.UpdateMeal(Meal))
            {
                return Redirect("/Meal");
            }
            else
            {
                // Anders returnen we de view met eventuele validatie
                return View(Meal);
            }
        }

        [Authorize]
        [HttpPost]
        // Post request met nieuwe maaltijd
        public IActionResult NewMeal(Meal Meal)
        {
            // Zet het user id om in een applicationuser
            Meal.Cook = UserRepository.Users.Where(e => e.Id == User.FindFirstValue(ClaimTypes.NameIdentifier)).FirstOrDefault();
            
            // Indien de maaltijd goed toegevoegd is dan gaan we terug naar het maaltijden overzicht
            if (MealRepository.CreateMeal(Meal))
            {
                return Redirect("/Meal");
            } else
            {
                // Indien dit fout ging returnen we de maaltijd en geven we aan dat er al een maaltijd gepland is
                ModelState.AddModelError("Date", "A meal is already planned on this day");
                return View(Meal);
            }
        }

        // Sluit je aan bij een maaltijd
        [Authorize]
        [HttpPost]
        public IActionResult JoinMeal(MealButtonViewModel MealButtonViewModel)
        {
            // Krijg de maaltijd vanuit het ID
            Meal Meal = MealRepository.Meals.Where(e => e.ID == MealButtonViewModel.MealID).FirstOrDefault();

            // Zit hij niet al vol?
            if (Meal?.Eaters?.Count >= Meal.MaxAmountOfGuests) return View("Error");

            // Voeg gebruiker toe
            if (MealRepository.JoinMeal(MealButtonViewModel.MealID, User?.FindFirstValue(ClaimTypes.NameIdentifier) ?? "")) {
                return Redirect("/Meal");
            }
            else
            {
                return View("Error");
            }
        }

        [Authorize]
        [HttpPost]
        // Verlaat een maaltijd
        public IActionResult LeaveMeal(MealButtonViewModel MealButtonViewModel)
        {
            if (MealRepository.LeaveMeal(MealButtonViewModel.MealID, User.FindFirstValue(ClaimTypes.NameIdentifier)))
            {
                return Redirect("/Meal");
            }
            else
            {
                return View("Error");
            }
        }

        // Verwijder een maaltijd
        [Authorize]
        [HttpPost]
        public IActionResult DeleteMeal(MealButtonViewModel MealButtonViewModel)
        {
            // Krijg het maaltijd object
            Meal Meal = MealRepository.Meals.Where(e => e.ID == MealButtonViewModel.MealID).FirstOrDefault();

            // Bekijk of maaltijd leeg is
            if (Meal.Eaters.Count != 0) return View("Error");

            // Bekijk of gebruiker wel de kok is
            if (User != null && !Meal.Cook.Id.Equals(User.FindFirstValue(ClaimTypes.NameIdentifier))) return View("Error");

            // Verwijder maaltijd
            if (MealRepository.DeleteMeal(MealButtonViewModel.MealID))
            {
                return Redirect("/Meal");
            }
            else
            {
                return View("Error");
            }
        }
    }
}

StudentenHuis/Views/Shared/MealSummary.cshtml
@model Meal


<div class="card">
    <div class="card-body">
        
        <div class="d-flex w-100 justify-content-between">
            <a asp-controller="Meal" asp-action="Detail" asp-route-id="@Model.ID">
                <h4>@(Model.Title ?? "No title vailable")</h4>
            </a>
            <p style="white-space: nowrap">⏰ @(Model.Date.ToString() ?? "No date available")</p>
        </div>
        
        <div class="d-flex w-100 justify-content-between">
            <div>
                <p class="card-text">👨 @(Model?.Eaters?.Count ?? 0) / @Model.MaxAmountOfGuests</p>
                <p class="card-text">
                    <button type="button" class="btn btn-dark btn-sm btn-block" data-toggle="collapse" data-target="#cookMeal_@(Model.ID)_@(Model.Cook.Id)" aria-expanded="false" aria-controls="collapseCook">🍳 @(Model.Cook?.Fullname() ?? "?")</button>
                </p>
                <div class="collapse" id="cookMeal_@(Model.ID)_@(Model.Cook.Id)">
                    <span style="display: none">@(ViewBag.PreventStackOverflow = false)</span>
                    @Html.Partial("UserSummary", Model.Cook)
                </div>
            </div>
            <div>
                <p class="card-text">💰 @Model.Price</p>
                @await Component.InvokeAsync("MealButtons", Model)
            </div>
        </div>
    </div>
</div>

StudentenHuis/Views/Shared/UserSummary.cshtml
@model ApplicationUser


<div class="card">
    <div class="card-body">
        <h4>@(Model?.Fullname() ?? "No name available")</h4>
        <p class="card-text" style="margin-bottom:2px">📧 @(Model?.Email ?? "No email available")</p>
        <p class="card-text">☎ @(Model?.PhoneNumber ?? "No phonenumber available")</p>
        @if(ViewBag?.PreventStackOverflow ?? true)
        {
        <button type="button" class="btn-dark btn btn-sm" data-toggle="collapse" data-target="#mealsToggleID_@Model?.Id" aria-expanded="false" aria-controls="collapseExample">🍝 Joins</button>
        <button type="button" class="btn btn-dark btn-sm" data-toggle="collapse" data-target="#cooksToggleID_@Model?.Id" aria-expanded="false" aria-controls="collapseExample">🍳 Cooks</button>
        <div class="collapse" id="mealsToggleID_@Model?.Id">
            @foreach (var Meal in Model.MealsAsEater)
            {
                @Html.Partial("MealSummary", Meal.Meal);

            }
            @if (Model.MealsAsEater.Count() < 1)
            {
                <div class="card">
                    <div class="card-body">
                        <p class="card-text">@Model.Firstname hasn't joined any meals yet</p>
                    </div>
                </div>
            }
        </div>
        <div id="cooksToggleID_@Model?.Id" class="collapse">
            @foreach (var Meal in Model.MealsAsCook)
            {
                @Html.Partial("MealSummary", Meal);

            }
            @if (Model.MealsAsCook.Count() < 1)
            {
                <div class="card">
                    <div class="card-body">
                        <p class="card-text">@Model.Firstname has not cooked anything yet</p>
                    </div>
                </div>
            }
        </div>
        }
    </div>
</div>

StudentenHuis/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>StudentenHuis - @(ViewData["title"] ?? "Time to eat!")</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" asp-href-include="~/css/bundle.css" />
    <link rel="shortcut icon" asp-href-include="/favicon.png">
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg mainnav">
            <a href="/" class="navbar-brand">Student Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon" />
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" asp-action="Index" asp-controller="Meal">Meals</a>
                    <a class="nav-item nav-link" asp-action="Index" asp-controller="Account">Users</a>
                    <a class="nav-item nav-link" asp-action="NewMeal" asp-controller="Meal">Add a new meal</a>
                </div>
            </div>
        </nav>
        <div class="row">
            <main class="col-md-8">
                @RenderBody()
            </main>
            <aside class="col-md-4">
                @await Component.InvokeAsync("Sidebar")
            </aside>
        </div>
        <div style="margin-top: 10em"></div>
        <footer class="fixed-bottom text-center">
            © Heijden Solutions 2018
        </footer>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script src="~/js/main.js" asp-append-version="true"></script>
</body>
</html>